#!/bin/bash

timeout 2.3s rostopic pub -r 10 /uav1/cmd_vel geometry_msgs/Twist "linear:
  x: 0.0
  y: 0.0
  z: 1.0
angular:
  x: 0.0
  y: 0.0
  z: 0.0" &
sleep 1

timeout 2s rostopic pub -r 10 /uav1/cmd_vel geometry_msgs/Twist "linear:
  x: 0.0
  y: 0.0
  z: 0.0
angular:
  x: 0.0
  y: 0.0
  z: 0.0" 

timeout 2s rostopic pub -r 10 /uav2/cmd_vel geometry_msgs/Twist "linear:
  x: 0.0
  y: 0.0
  z: 1.0
angular:
  x: 0.0
  y: 0.0
  z: 0.0" &
sleep 1

timeout 2.1s rostopic pub -r 10 /uav2/cmd_vel geometry_msgs/Twist "linear:
  x: 0.0
  y: 0.0
  z: 0.0
angular:
  x: 0.0
  y: 0.0
  z: 0.0" 
sleep 1

timeout 2s rostopic pub -r 10 /uav3/cmd_vel geometry_msgs/Twist "linear:
  x: 0.0
  y: 0.0
  z: 1.0
angular:
  x: 0.0
  y: 0.0
  z: 0.0" &
sleep 1

timeout 2.1s rostopic pub -r 10 /uav3/cmd_vel geometry_msgs/Twist "linear:
  x: 0.0
  y: 0.0
  z: 0.0
angular:
  x: 0.0
  y: 0.0
  z: 0.0" 
sleep 1

timeout 2s rostopic pub -r 10 /uav4/cmd_vel geometry_msgs/Twist "linear:
  x: 0.0
  y: 0.0
  z: 1.0
angular:
  x: 0.0
  y: 0.0
  z: 0.0" &
sleep 1

timeout 2.1s rostopic pub -r 10 /uav4/cmd_vel geometry_msgs/Twist "linear:
  x: 0.0
  y: 0.0
  z: 0.0
angular:
  x: 0.0
  y: 0.0
  z: 0.0" 

sleep 1
gnome-terminal --tab -e "roslaunch multiple_quadrotor_nav explore1.launch" &
gnome-terminal --tab -e "roslaunch multiple_quadrotor_nav explore2.launch" &
gnome-terminal --tab -e "roslaunch multiple_quadrotor_nav explore3.launch" &
gnome-terminal --tab -e "roslaunch multiple_quadrotor_nav explore4.launch" &
gnome-terminal --tab -e "./b8" &
gnome-terminal --tab -e "rosrun teleop_twist_keyboard test.py"